eureka:
  client:
    register-with-eureka: true
server:
  port: 8080
spring:
  application:
     name: API_Gateway   
                
  cloud: 
    gateway: 
      globalcors:
          corsConfigurations:
            '[/**]':
              allowedOrigins: "*"
              allowedHeaders: "*"
              allowedMethods: "*"     
      routes:
      - id: admin
        uri: 
          lb://Admin-Service
        predicates:
        - Path=/admin/**
      - id: checkIn
        uri: lb://Checkin-microservice/checkIn
        predicates:
        - Path=/checkIn/**
      - id: book
        uri: lb://booking-microservice/book
        predicates:
        - Path=/book/**
      - id: pay
        uri: lb://payment-service/pay
        predicates:
        - Path=/pay/**
      - id: user
        uri: lb://Userservice/users
        predicates:
        - Path=/users/**
      
            